#!/bin/sh

# Define a WSGI script for a wiki.
#
# Copyright (C) 2023 Paul Boddie <paul@boddie.org.uk>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA  02110-1301, USA

SITENAME=$1
SITEROOT=${2:-"/var/www"}

if [ ! "$SITENAME" ] ; then
    echo "Please indicate a site name." 1>&2
    exit 1
fi

SITEDIR="$SITEROOT/$SITENAME"

if [ ! -d "$SITEDIR" ] ; then
    echo "Web site directory $SITEDIR does not exist." 1>&2
    exit 1
fi

# Replace parameters in the WSGI script given below.

cat <<EOF > "$SITEDIR/$SITENAME.wsgi"
from moin.app import create_app
application = create_app("$SITEDIR/wikiconfig.py")
EOF
