#!/bin/sh

# Define an Apache site configuration for a wiki.
#
# Copyright (C) 2023 Paul Boddie <paul@boddie.org.uk>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA  02110-1301, USA

SITENAME=$1
CONFDIR=${2:-"/etc/apache2/sites-available"}

if [ ! "$SITENAME" ] ; then
    echo "Please indicate a site name." 1>&2
    exit 1
fi

if [ ! -d "$CONFDIR" ] ; then
    echo "Apache configuration directory $CONFDIR does not exist." 1>&2
    exit 1
fi

# Replace parameters in the site definition given below.

cat <<EOF > "$CONFDIR/$SITENAME.conf"
WSGIScriptAlias /wiki /var/www/$SITENAME/$SITENAME.wsgi
WSGIDaemonProcess $SITENAME
WSGIProcessGroup $SITENAME
EOF
